### ISSUE TITLE
PS Lab Logo missing

### ISSUE THREAD

**Issue by anilmaurya61** [fossasia/pslab-documentation#120]
Screenshot for better understand

![ps lab](https://user-images.githubusercontent.com/56387037/91034094-0bd4e680-e622-11ea-8e23-532424aa7aef.jpg)

**Comment by nikhanal** [comment]
Can I work on this issue?

**Comment by bessman** [comment]
Sure! [This logo](https://github.com/fossasia/pslab-android/blob/development/app/src/main/res/drawable/logo.png) should be displayed there.

**Comment by nikhanal** [comment]
I am new to open source projects can you me guide me?

**Comment by bessman** [comment]
Sure. The documentation is written in Sphinx. The [readme](https://github.com/fossasia/pslab-documentation/blob/master/Readme.md) explains how to build the documentation website. The layout of the generated website is defined in [conf.py](https://github.com/fossasia/pslab-documentation/blob/master/conf.py). If you look at [Sphinx's documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html) you should be able to figure out how to add the logo.

**Comment by nikhanal** [comment]
Is this ok?
![Capture](https://user-images.githubusercontent.com/66510055/91192968-4f108180-e716-11ea-9dcb-421bee700a23.PNG)

**Comment by bessman** [comment]
Yes, that looks good! Please open a pull request.

**Comment by anilmaurya61** [comment]
> Is this ok?
> ![Capture](https://user-images.githubusercontent.com/66510055/91192968-4f108180-e716-11ea-9dcb-421bee700a23.PNG)

**Comment by anilmaurya61** [comment]
> Is this ok?
> ![Capture](https://user-images.githubusercontent.com/66510055/91192968-4f108180-e716-11ea-9dcb-421bee700a23.PNG)

Yes! Please open PR with preview link.

**Comment by swapnilsparsh** [comment]
Can I work on this issue ?

**Comment by bessman** [comment]
From the looks of it @nikhanal has already fixed it. However, they haven't opened a pull request yet. @nikhanal, please do so as soon as possible.

@swapnilsparsh, let's wait until after the weekend. If no PR has been opened by then, feel free to start working on this issue.

**Comment by nikhanal** [comment]
I am really sorry that I was late.
I have opened the pull request please view it.

**Comment by orangecms** [comment]
Done in #121 - thank you a lot @nikhanal :)

**Comment by nikhanal** [comment]
> Done in #121 - thank you a lot @nikhanal :)

My pleasure
