### ISSUE TITLE
Missing Experiments in README file

### ISSUE THREAD

**Issue by harsh-2711** [fossasia/pslab-documentation#13]
Following experiments are not placed in README file although there documentations are available in experiments folder

- Capacitor Discharging

- Linear Ramp Generator

- Electromagnetic Induction

- Piezo Buzzer

- Ultrasonic Range Finder

- Transient RLC Response

- Piezo Bandwidth Characteristics

- RC Integrals, Derivatives

**Comment by ananyaarun** [comment]
@harsh-2711 can i work on this ?

**Comment by harsh-2711** [comment]
@ananyaarun  I have made the PR and it will soon be accepted after I do proposed changes, So, you can better work on other issue
