### ISSUE TITLE
Change theme of experiment page

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-documentation#37]
The experiment page has a greenish background which should be changed to match PSLab's theme.

**Comment by priyanshunayan** [comment]
I would like to solve this issue. Can I proceed?

**Comment by AakashMallik** [comment]
@priyanshunayan Go ahead

**Comment by priyanshunayan** [comment]
@AakashMallik I have created a pull request. Please review it.

**Comment by priyanshunayan** [comment]
This issue should be closed now.
