### ISSUE TITLE
Add PR and issue template for this repository

### ISSUE THREAD

**Issue by AakashMallik** [fossasia/pslab-documentation#38]
PR and issue template missing from this repo.

Should be added to make it easier for developers to raise issues and PRs.

**Comment by priyanshunayan** [comment]
@AakashMallik  PR template can be added as a file but adding issue template as a file is considered a legacy workflow. How can I add the issue template alternatively as I don't have the access to the Settings->Features->Issues->set up template?

**Comment by AakashMallik** [comment]
> @AakashMallik PR template can be added as a file but adding issue template as a file is considered a legacy workflow. How can I add the issue template alternatively as I don't have the access to the Settings->Features->Issues->set up template?

Curious why adding issue file is considered legacy. Need some supporting doc to agree upon that right now.

**Comment by priyanshunayan** [comment]
@AakashMallik I read this thing here. [Link](https://help.github.com/en/articles/manually-creating-a-single-issue-template-for-your-repository)

**Comment by AakashMallik** [comment]
@priyanshunayan That doc states that this workflow is legacy as this will allow you to create a **single** issue template file for the whole repo. And for creating **multiple** issue template, they suggest using the new workflow. Do we need multiple issue templates right now? The answer is no. So the template file method should work just fine for now. 

:-)

**Comment by AakashMallik** [comment]
Take reference from the PSLab Desktop repo. We have a PR template and Issue template in place. make needful modifications and copy paste..

**Comment by priyanshunayan** [comment]
@AakashMallik Got it. Thank you so much. :)  I am onto it.

**Comment by priyanshunayan** [comment]
@AakashMallik  I have added the files but when I opened the issue template of pslab-dektop, i was seeing this message. 
![image](https://user-images.githubusercontent.com/32892545/63541667-363a2280-c53c-11e9-8f66-1edbba3fb9fb.png)

**Comment by CloudyPadmal** [comment]
Yes, there's a new workflow where the first three options can be set by GitHub itself. https://github.com/fossasia/neurolab-android/issues/new/choose

**Comment by AakashMallik** [comment]
> Yes, there's a new workflow where the first three options can be set by GitHub itself. https://github.com/fossasia/neurolab-android/issues/new/choose

@CloudyPadmal Should we switch to the new workflow??

**Comment by CloudyPadmal** [comment]
Sure we can. https://github.com/fossasia/pslab-documentation/pull/41 check this one and suggest changes if anything's needed
