### ISSUE TITLE
Convert rst to md and ensure the documentation builds

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab-documentation#49]
Most FOSSASIA repos are using MD files. In order to be able to easily copy from one repo to another for the user documentation here, please convert the rst files to md files.

**Comment by vidhyav656** [comment]
Can I work on it? Please assign to me.

**Comment by mariobehling** [comment]
Go ahead. No need to ask.

**Comment by vidhyav656** [comment]
@Dishebh I am also working on it.

**Comment by Dishebh** [comment]
> @Dishebh I am also working on it.

@vidhyav656 cool, I won't interfere then. Just let me know incase if I can join you in it. Or you can just solve it on your own.

**Comment by orangecms** [comment]
With #50 merged, I am closing this. Thank you!
