### ISSUE TITLE
Changes for Grammatical errors.

### ISSUE THREAD

**Issue by abhrakantidubey** [fossasia/pslab-documentation#61]
**Describe the issue**

**Would you like to work on the issue?**
# pslab-Compass
PSLab Documentation and Experiments https://docs.pslab.io
# EXPERIMENT TO CHECK THAT PSLab-COMPASS DEFLECTS WHEN IT COMES IN CONTACT WITH MAGNET.
+ 1.REQUIREMENTS:
Android phone with a) compass sensor and b) PSLab app installed, magnet and a compass.
 1.STEPS:
 STEP 1:
Take the magnet near to the compass. You will see that the compass is deflecting.
STEP 2:
Take the magnet near to the PSLab-Compass. You will see that, there is no deflection in it.
+ 3.RESULT:
 Through this experiment, it shows that Magnets do interact with the magnet inside a normal but that show no effect on the PSLab-compass.
+ 4.CONCLUSION:
By this Experiment, we can understand that the PSLab compass uses GPS and other sensors to provide us directions and Do not uses any magnet to find directions. It further examines the GPS and Sensor readings and then using this data calibrate the compass needles according to our phone calibration and general position.
YOU CAN CHECK THE SCREENSHOTS.
Ps-lab compass near the magnet
![WhatsApp Image 2020-01-03 at 10 30 57 AM](https://user-images.githubusercontent.com/58810632/71708067-9313e680-2e14-11ea-916b-ca6292d48647.jpeg)
Ps-lab compass normal
![WhatsApp Image 2020-01-03 at 10 30 57 AM (1)](https://user-images.githubusercontent.com/58810632/71708102-d4a49180-2e14-11ea-8731-1bd64660709b.jpeg)

**Comment by orangecms** [comment]
Closing this as the related issue #59 is also closed and due to inactivty.
