### ISSUE TITLE
Questions Regarding how to use the Compass in PSLab as well as How it Works

### ISSUE THREAD

**Issue by aryanguls2** [fossasia/pslab-documentation#83]
**Describe the issue**
While most people have become fairly acquainted with the idea of everything becoming digital, few know how to use such applications and the inner working of such gadgets

**Would you like to work on the issue?**
Yes I would like to work on the issue.

**Comment by mariobehling** [comment]
There should not be a FAQ for every instrument at this point of time. Especially there is no point in repeating general information in an FAQ. Therefore closing it.
